In [311]:
import pandas as pd
import json
import openpyxl

In [353]:
#pip install openpyxl
#pip install contentful-management

In [336]:
# Step 1: Read the Excel file

excel_file_path = './2CATALOGO COMPLETO_Revision FLB, NFF para Docwell PICS.xlsx'
xls = pd.ExcelFile(excel_file_path)
catalog_sheet = pd.read_excel(xls, "NFF existen en FLB completo", skiprows=3)

In [315]:
catalog_sheet.head()

,Artículo,Status,Nombre,Descripción,Detalles,Ingredientes,Indicaciones,Etiquetas,Cloud,ATC,Departamento,Categoria,Principio Activo,% Impuesto,Unid. Conversion,Código Casa,Nombre Casa,Estupefacientes y Psicotrópicos
0,210604,IN,BANANA BOAT SPORT SPRAY 170 ML,Venta por unidad,Los protectores Banana Boat te protegen de lo...,SIN ASIGNAR,NaN,"Bloqueador solar, Para deporte, Protector sola...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,212241,IN,BANANA BOAT GENTLE PROTECT KIDS 220 ML,Venta por Unidad,•Proporciona protección UVA / UVB de amplio es...,NaN,NaN,"Bloqueador solar, Filtro solar, Niño, Infantil",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,212265,IN,BANANA BOAT GENTLE PROTECT KIDS 180 ML,Venta por Unidad,Previene quemaduras solares. • Fórmula de ampl...,NaN,NaN,"Bloqueador solar, Niño, Protector solar",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,212289,IN,BANANA BOAT GENTLE PROTECT BABY 180 ML,Venta por unidad,Proporciona protección UVA / UVB de amplio esp...,NaN,NaN,Bloqueador solar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,215243,IN,BANANA BOAT DRY BALANCE SPRAY 170 ML,Venta por unidad,"Nueva loción Dry Balance Sport, ayuda a sentir...",BLOQUEADOR SOLAR,NaN,"Bloqueador solar, Para deporte, Protector sola...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [316]:
print("DataFrame Shape:", catalog_sheet.shape)
print("\nDataFrame Info:")
display(catalog_sheet.info())

print("\nMissing Values Summary:")
display(catalog_sheet.isna().sum())

print("\nStatistical Summary (All Columns):")
display(catalog_sheet.describe(include='all'))

print("\nSample Data:")
display(catalog_sheet.sample(5))

DataFrame Shape: (4113, 18)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4113 entries, 0 to 4112
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Artículo                         4108 non-null   object
 1   Status                           4107 non-null   object
 2   Nombre                           4108 non-null   object
 3   Descripción                      4101 non-null   object
 4   Detalles                         3762 non-null   object
 5   Ingredientes                     3072 non-null   object
 6   Indicaciones                     2781 non-null   object
 7   Etiquetas                        2783 non-null   object
 8   Cloud                            2980 non-null   object
 9   ATC                              2395 non-null   float64
 10  Departamento                     2980 non-null   object
 11  Categoria                        2980 non-null   object
 12  Principio Activo                 2980 non-null   object
 13  % Impuesto                       2980 non-null   float64
 14  Unid. Conversion                 2980 non-null   float64
 15  Código Casa                      2980 non-null   float64
 16  Nombre Casa                      2980 non-null   object
 17  Estupefacientes y Psicotrópicos  15 non-null     object
dtypes: float64(4), object(14)
memory usage: 578.5+ KB

None

Missing Values Summary:

Artículo                              5
Status                                6
Nombre                                5
Descripción                          12
Detalles                            351
Ingredientes                       1041
Indicaciones                       1332
Etiquetas                          1330
Cloud                              1133
ATC                                1718
Departamento                       1133
Categoria                          1133
Principio Activo                   1133
% Impuesto                         1133
Unid. Conversion                   1133
Código Casa                        1133
Nombre Casa                        1133
Estupefacientes y Psicotrópicos    4098
dtype: int64

Statistical Summary (All Columns):

,Artículo,Status,Nombre,Descripción,Detalles,Ingredientes,Indicaciones,Etiquetas,Cloud,ATC,Departamento,Categoria,Principio Activo,% Impuesto,Unid. Conversion,Código Casa,Nombre Casa,Estupefacientes y Psicotrópicos
count,4108.0,4107,4108,4101,3762,3072,2781,2783,2980,2.395000e+03,2980,2980,2980,2980.000000,2980.000000,2980.000000,2980,15
unique,4095.0,5,4015,670,1341,1546,675,1515,2878,NaN,18,146,673,NaN,NaN,NaN,182,1
top,3740211.0,AC,PARA DENK 125 MG SUPOSITORIOS,Venta por unidad,• Consulte a su médico antes de consumir cualq...,SIN ASIGNAR,No se recomienda el consumo de este medicament...,Hipertensión,EMB100270,NaN,AGUDOS RX,TERAPIA TOPICA,SIN ASIGNAR,NaN,NaN,NaN,MEGALABS,x
freq,2.0,2868,2,996,1640,122,317,107,2,NaN,1030,199,603,NaN,NaN,NaN,167,15
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.944494e+06,NaN,NaN,NaN,4.870805,1.932886,596.599664,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.753324e+06,NaN,NaN,NaN,4.981175,8.417652,207.080733,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,0.000000,1.000000,21.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.058520e+05,NaN,NaN,NaN,2.000000,1.000000,459.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.900929e+06,NaN,NaN,NaN,2.000000,1.000000,603.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.657570e+06,NaN,NaN,NaN,13.000000,1.000000,744.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.665359e+06,NaN,NaN,NaN,13.000000,250.000000,985.000000,NaN,NaN

Sample Data:

,Artículo,Status,Nombre,Descripción,Detalles,Ingredientes,Indicaciones,Etiquetas,Cloud,ATC,Departamento,Categoria,Principio Activo,% Impuesto,Unid. Conversion,Código Casa,Nombre Casa,Estupefacientes y Psicotrópicos
3046,7290008,IN,OZEMPIC DUALDOSE 0.25MG/0.5MG/ML SOLUCIÓN INYE...,La entrega cumple con aseguramiento de cadena ...,• Consultá a tu médico antes de consumir cualq...,Semaglutida,• No utilice Ozempic® si usted es alérgico a S...,Diabetes,FAR105467,NaN,CRÓNICOS RX,INSULINAS,SIN ASIGNAR,2.0,1.0,729.0,NOVO NORDISK,NaN
1105,3744016,AC,EUCERIN HIAURON-FILLER + ELASTICITY CREMA FACI...,Venta por unidad,Tratamiento de día que combate las líneas de e...,Ácido hialurónico de alto y bajo peso molecula...,NaN,"Antiarrugas, Antiedad, Arrugas",CON100119,NaN,BELLEZA SELECTIVO,ANTIARRUGAS,SIN ASIGNAR,13.0,1.0,374.0,BDF,NaN
55,888614,IN,FÓRMULA PURA DH CONCEALER 03,Venta por unidad,Corrector en barra enriquecido con un cóctel d...,"INGREDIENTS: TRIETHYLHEXANOIN, CAPRYLIC/CAPRIC...",NaN,"Cara, Maquillaje, Rostro",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2054,5821209,AC,HUGGIES PAÑAL NATURAL CARE RECIÉN NACIDO 20 UN...,Empaque con 20 unidades,Pañales Huggies® Natural Care: Nuestra mejor p...,NaN,NaN,"Bebé, Pañalitis",EMB100083,1896202.0,INFANTIL,PAÑALES,SIN ASIGNAR,1.0,1.0,582.0,KIMBERLY CLARK,NaN
3805,9131960,AC,FLUCONAZOL 200 MG TABLETAS VIA ORAL 1+1,Caja con 1 unidad,• Consulte a su médico antes de consumir cualq...,FLUCONAZOL,• No se recomienda el consumo de este medicame...,Hongos,FAR100806,3891130.0,AGUDOS RX,TRATAMIENTO DE LAS ENFERMEDADES POR HONGOS,FLUCONAZOL,2.0,1.0,913.0,CALOX,NaN

In [317]:
def describe_dataframe(df):
    for column in df.columns:
        print(f"=== Column: {column} ===\n")
        
        # Show basic information
        print(f"Data Type: {df[column].dtype}")
        
        # Show unique values
        print(f"Unique Values:\n{df[column].unique()}\n")
        
        # Show value counts
        print(f"Value Counts:\n{df[column].value_counts()}\n")
        
        # Show missing data summary
        missing_count = df[column].isna().sum()
        print(f"Missing Values: {missing_count} out of {df.shape[0]}")
        
        print("\n" + "="*50 + "\n")

In [340]:
len(catalog_sheet["Categoria"].unique())

147

In [341]:
categories_unique = catalog_sheet["Categoria"]

In [342]:
import re

def create_slug(string):
    # Convert to lowercase
    string = string.lower()
    # Replace spaces with hyphens
    string = string.replace(" ", "-")
    # Remove any characters that are not alphanumeric or hyphens
    string = re.sub(r'[^a-z0-9\-]', '', string)
    if string.startswith("_"):
        string = string[1:]
    return string

def capitalize_first_letter(string):
    return string[0].upper() + string[1:].lower()

def create_id(category_name):
    category_name = category_name.lower().replace(" ", "_")
    if category_name.startswith("_"):
        category_name = category_name[1:]
    if category_name.endswith("_"):
        category_name = category_name[1:]
    return category_name


categories = []
category_map = {}  # To map category names to IDs

for row in categories_unique:
    if type(row) == str:
        category_name = capitalize_first_letter(row)
        
        # Check if the category already exists in the category_map
        if category_name in category_map:
            continue  # Skip this category if it already exists

        category_handle = create_slug(row)
        
        # Generate the category_id by converting the name to lowercase and replacing spaces with underscores
        category_id = create_id(category_name)
        
        category_map[category_name] = category_id

        category = {
            "id": category_id,
            "name": category_name,
            "rank": 0,
            "category_children": [],
            "handle": category_handle
        }
        categories.append(category)

In [343]:
def create_options(description):
    # Use a regular expression to split the description by "y", "/", or "-"
    values = re.split(r'\s*[y/-]\s*', str(description))
    
    # Create the options object
    options = [
        {
            "title": "Formato",
            "values": values
        }
    ]
    return options

def create_variants(options, base_price, currency="crc", inventory_quantity=100):
    variants = []
    # print(options)
    # Iterate over the values in the "Formato" option
    for value in options[0]["values"]:
        title = value  # Title is simply the value in this case
        variant = {
            "title": title,
            "prices": [
                {
                    "currency_code": currency,
                    "amount": base_price
                }
            ],
            "options": [
                {"value": value}
            ],
            "inventory_quantity": inventory_quantity,
            "manage_inventory": False
        }
        variants.append(variant)
    
    return variants

In [344]:
import numpy as np
import pandas as pd

def is_nan(string):
    if pd.isna(string):
        return ""
    else:
        return string

def get_description(row):
    description = row["Detalles"]
    return is_nan(description)

def transform_tags(tag_string):
    tags = tag_string.split(',')
    return [{"value": tag.strip()} for tag in tags]

def find_product_by_handle(products, handle):
    for product in products:
        if product["handle"] == handle:
            return product
    return None

products = []
for _, row in catalog_sheet.iterrows():
    if pd.notna(row["Nombre"]):
        options = create_options(row["Descripción"])
        handle = create_slug(str(row["Nombre"]))
        product = {
                "title": row["Nombre"],
                "categories":[],
                "description": get_description(row),
                "handle": handle,
                "is_giftcard": False,
                "weight": None,  # Populate as necessary
                "images": [],  # Populate as necessary from the Excel
                "options": options,
                "variants": create_variants(options, 1950),
                "metadata": {}
            }

        # Assign category
        category_name = row["Categoria"]
        if category_name in category_map:
            product["categories"] = [{"id": category_map[category_name]}]

        # Handle labels/tags
        if pd.notna(row["Etiquetas"]):
            product["tags"] = transform_tags(row["Etiquetas"])
        else:
            product["tags"] = []

        # Step 4: Handle metadata
        metadata_fields = ["Ingredientes", "Indicaciones", "Cloud", "ATC", "Principio Activo", 
                        "% Impuesto", "Código Casa", "Nombre Casa", "Estupefacientes y Psicotrópicos"]
        for field in metadata_fields:
            if field in row and pd.notna(row[field]):
                product["metadata"][field] = row[field]

        # Check if product with the same handle exists
        existing_product = find_product_by_handle(products, handle)
        if existing_product:
            # Compare the number of tags and keep the one with more tags
            if len(product["tags"]) > len(existing_product["tags"]):
                products.remove(existing_product)
                products.append(product)
        else:
            products.append(product)

In [345]:
header = {
  "store": {
    "currencies": ["eur","crc"]
  },
  "users": [
    {
      "email": "admin@test.com",
      "password": "supersecret"
    }
  ],
  "regions": [
    {
      "id": "region-cr",
      "name": "CR",
      "currency_code": "crc",
      "tax_rate": 13,
      "payment_providers": ["manual"],
      "fulfillment_providers": ["manual"],
      "countries": ["cr"]
    }
  ],
  "shipping_options": [
    {
      "name": "Manual Standard",
      "region_id": "region-cr",
      "provider_id": "manual",
      "data": {
        "id": "manual-fulfillment"
      },
      "price_type": "flat_rate",
      "amount": 1000
    },
    {
      "name": "Manual Return",
      "region_id": "region-cr",
      "provider_id": "manual",
      "data": {
        "id": "manual-fulfillment"
      },
      "price_type": "flat_rate",
      "is_return": True,
      "amount": 1000
    },
    {
      "name": "I want to return it myself",
      "region_id": "region-cr",
      "provider_id": "manual",
      "data": {
        "id": "manual-fulfillment"
      },
      "price_type": "flat_rate",
      "is_return": True,
      "amount": 0
    }
  ],
}

In [346]:
header_test = {
  "store": {
    "currencies": ["eur","crc"]
  },
  "users": [

  ],
  "regions": [

  ],
  "shipping_options": [

  ],
}

In [347]:
# Step 5: Construct the final JSON structure
seed_data = {**header,  "products": products, "categories": categories}

# Save the JSON to a file
with open('./seed_output.json', 'w') as f:
    json.dump(seed_data, f, indent=2)

print("JSON file created successfully!")

JSON file created successfully!

In [348]:
import json
import numpy as np
import pandas as pd

def is_nan(string):
    if pd.isna(string):
        return ""
    else:
        return string

def get_description(row):
    description = row["Detalles"]
    return is_nan(description)

def transform_tags(tag_string):
    tags = tag_string.split(',')
    return [{"value": tag.strip()} for tag in tags]

def find_product_by_handle(products, handle):
    for product in products:
        if product["handle"] == handle:
            return product
    return None

def save_products_from_i_to_n(catalog_sheet, start, end, header, categories):
    products = []
    counter = 0

    for index, row in catalog_sheet.iterrows():
        if counter >= end - start + 1:
            break

        if index >= start and pd.notna(row["Nombre"]):
            options = create_options(row["Descripción"])
            handle = create_slug(str(row["Nombre"]))
            product = {
                "title": row["Nombre"],
                "categories":[],
                "description": get_description(row),
                "handle": handle,
                "is_giftcard": False,
                "weight": None,  # Populate as necessary
                "images": [],  # Populate as necessary from the Excel
                "options": options,
                "variants": create_variants(options, 1950),
                "metadata": {}
            }

             # Assign category
            category_name = row["Categoria"]
            if category_name in category_map:
                print("Estoy en categoria")
                new_categories = [{"id": category_map[category_name]}]
                print(new_categories)
                product["categories"] = product["categories"] + new_categories

            # Handle labels/tags
            if pd.notna(row["Etiquetas"]):
                product["tags"] = transform_tags(row["Etiquetas"])
            else:
                product["tags"] = []

            # Step 4: Handle metadata
            metadata_fields = ["Ingredientes", "Indicaciones", "Cloud", "ATC", "Principio Activo", 
                            "% Impuesto", "Código Casa", "Nombre Casa", "Estupefacientes y Psicotrópicos"]
            for field in metadata_fields:
                if field in row and pd.notna(row[field]):
                    product["metadata"][field] = row[field]

            # Check if product with the same handle exists
            existing_product = find_product_by_handle(products, handle)
            if existing_product:
                # Compare the number of tags and keep the one with more tags
                if len(product["tags"]) > len(existing_product["tags"]):
                    products.remove(existing_product)
                    products.append(product)
            else:
                products.append(product)
                counter += 1  # Increment the counter only if a new product is added

    # Step 5: Construct the final JSON structure
    seed_data = {**header, "products": products, "categories": categories}

    # Step 6: Create a dynamic filename based on the range
    filename = f'./seed_output_{start}_to_{end}.json'


    # Step 7: Save the JSON to a file
    with open(filename, 'w') as f:
        json.dump(seed_data, f, indent=2)

    print(f"JSON file '{filename}' created successfully!")

In [349]:
# Example usage:
save_products_from_i_to_n(catalog_sheet, 251, 500, header_test, categories)

JSON file './seed_output_251_to_500.json' created successfully!

In [350]:
len(categories)

146